version: "3.8"

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - main
    restart: "unless-stopped"

networks:
  main:
    driver: bridge
