export const vehicleMock = {
  name: 'TIE/LN starfighter',
  model: 'Twin Ion Engine/Ln Starfighter',
  manufacturer: 'Sienar Fleet Systems',
  cost_in_credits: 'unknown',
  length: '6.4',
  max_atmosphering_speed: '1200',
  crew: '1',
  passengers: '0',
  cargo_capacity: '65',
  consumables: '2 days',
  vehicle_class: 'starfighter',
  pilots: [],
  films: [
    'https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
  ],
  created: '2014-12-10T16:33:52.860000Z',
  edited: '2014-12-20T21:30:21.670000Z',
  url: 'https://swapi.dev/api/vehicles/8/',
};

export const vehiclesMock = {
  count: 39,
  next: 'https://swapi.dev/api/vehicles/?page=4',
  previous: 'https://swapi.dev/api/vehicles/?page=2',
  results: [
    {
      name: 'Zephyr-G swoop bike',
      model: 'Zephyr-G swoop bike',
      manufacturer: 'Mobquet Swoops and Speeders',
      cost_in_credits: '5750',
      length: '3.68',
      max_atmosphering_speed: '350',
      crew: '1',
      passengers: '1',
      cargo_capacity: '200',
      consumables: 'none',
      vehicle_class: 'repulsorcraft',
      pilots: ['https://swapi.dev/api/people/11/'],
      films: ['https://swapi.dev/api/films/5/'],
      created: '2014-12-20T16:24:16.026000Z',
      edited: '2014-12-20T21:30:21.714000Z',
      url: 'https://swapi.dev/api/vehicles/44/',
    },
    {
      name: 'Koro-2 Exodrive airspeeder',
      model: 'Koro-2 Exodrive airspeeder',
      manufacturer: 'Desler Gizh Outworld Mobility Corporation',
      cost_in_credits: 'unknown',
      length: '6.6',
      max_atmosphering_speed: '800',
      crew: '1',
      passengers: '1',
      cargo_capacity: '80',
      consumables: 'unknown',
      vehicle_class: 'airspeeder',
      pilots: ['https://swapi.dev/api/people/70/'],
      films: ['https://swapi.dev/api/films/5/'],
      created: '2014-12-20T17:17:33.526000Z',
      edited: '2014-12-20T21:30:21.716000Z',
      url: 'https://swapi.dev/api/vehicles/45/',
    },
  ],
};

export const mappedVehicleMock = {
  cargoCapacity: '65',
  consumables: '2 days',
  costInCredits: 'unknown',
  crew: '1',
  films: [
    'https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
  ],
  length: '6.4',
  manufacturer: 'Sienar Fleet Systems',
  maxAtmospheringSpeed: '1200',
  model: 'Twin Ion Engine/Ln Starfighter',
  name: 'TIE/LN starfighter',
  passengers: '0',
  pilots: [],
  url: 'https://swapi.dev/api/vehicles/8/',
  vehicleClass: 'starfighter',
};

export const mappedVehiclesMock = {
  count: 39,
  next: 'https://swapi.dev/api/vehicles/?page=4',
  previous: 'https://swapi.dev/api/vehicles/?page=2',
  results: [
    {
      cargoCapacity: '200',
      consumables: 'none',
      costInCredits: '5750',
      crew: '1',
      films: ['https://swapi.dev/api/films/5/'],
      length: '3.68',
      manufacturer: 'Mobquet Swoops and Speeders',
      maxAtmospheringSpeed: '350',
      model: 'Zephyr-G swoop bike',
      name: 'Zephyr-G swoop bike',
      passengers: '1',
      pilots: ['https://swapi.dev/api/people/11/'],
      url: 'https://swapi.dev/api/vehicles/44/',
      vehicleClass: 'repulsorcraft',
    },
    {
      cargoCapacity: '80',
      consumables: 'unknown',
      costInCredits: 'unknown',
      crew: '1',
      films: ['https://swapi.dev/api/films/5/'],
      length: '6.6',
      manufacturer: 'Desler Gizh Outworld Mobility Corporation',
      maxAtmospheringSpeed: '800',
      model: 'Koro-2 Exodrive airspeeder',
      name: 'Koro-2 Exodrive airspeeder',
      passengers: '1',
      pilots: ['https://swapi.dev/api/people/70/'],
      url: 'https://swapi.dev/api/vehicles/45/',
      vehicleClass: 'airspeeder',
    },
  ],
};
