FROM node:22.12.0-alpine3.20

RUN npm i -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

EXPOSE 3000 9229

ENV NODE_ENV=development

CMD [ "pnpm", "start:debug" ]
